Add blogs CRUD
James-nyagatare/MyBrand pull request #21
Opened 2020-11-21 14:07 UTC by James-nyagatare

#### What does this PR do?
-Add crud endpoints.
#### Description of Task to be completed?
-Add create, read, update and delete routes.
-Add multer for the photo to be uploaded.
-Add cloudinary to upload the image in the cloud.
#### How should this be manually tested?
-Postman
#### Questions:
N/A

2020-11-22 14:01 UTC, Mucyo-Aime-Christian commented
With my observations, this PR matches with my expectations. except if there is anything more from @harerakalex to request

2020-11-22 15:51 UTC, harerakalex requested changes
Well done @James-nyagatare, though I have got somethings that you can impprove.

2020-11-22 15:51 UTC, harerakalex commented on server/src/controllers/blogController.js
> +      console.log(error);
Well done @James-nyagatare, however, you should remove this console. That can give hackers information about what is happening in the system.

2020-11-22 15:51 UTC, harerakalex commented on server/src/config/cloudinary.js
> +    console.log(error);
You should return the error here instead of consoling the error.

2020-11-23 06:41 UTC, harerakalex approved these changes

2020-11-23 07:06 UTC, merged