Add admin dashboard
James-nyagatare/MyBrand pull request #8
Opened 2020-10-26 13:28 UTC by James-nyagatare

#### What does this PR do?
-Create Admin dashboard.
#### Description of Task to be completed?
-Create the structure of admin dashboard and implement it.
-Make the admin dashboard responsive
-Connect the admin dashboard to the relevant pages.
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/67368268/97178014-96ab9c00-179f-11eb-8536-94a2783f8875.png)
![image](https://user-images.githubusercontent.com/67368268/97178112-bb077880-179f-11eb-878e-e57844a47f49.png)

#### Questions:
N/A

2020-10-26 16:32 UTC, harerakalex requested changes
Well done @James-nyagatare , though you have to make a small improvement on your mobile responsiveness. 
![Screenshot from 2020-10-26 18-31-22](https://user-images.githubusercontent.com/39116572/97200219-9a4c1c80-17b9-11eb-9a91-137b7cdcbb44.png)

2020-10-27 05:37 UTC, James-nyagatare commented
> Well done @James-nyagatare , though you have to make a small improvement on your mobile responsiveness.
> ![Screenshot from 2020-10-26 18-31-22](https://user-images.githubusercontent.com/39116572/97200219-9a4c1c80-17b9-11eb-9a91-137b7cdcbb44.png)

I accidentally pushed the things of the new feature I was working on please do not mind them for the moment.

2020-10-27 05:39 UTC, harerakalex approved these changes

2020-10-27 05:42 UTC, harerakalex requested changes
@James-nyagatare, everything is good except the responsiveness of the iPhone 5/SE, kindly consider fixing it. Look at the navbar.
![Screenshot from 2020-10-27 07-38-04](https://user-images.githubusercontent.com/39116572/97261566-c1d9ce00-1827-11eb-8f32-1365a2f95f4f.png)

2020-10-27 06:30 UTC, harerakalex approved these changes

2020-10-27 06:49 UTC, merged